apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snoHostPath
spec:
  crd:
    spec:
      names:
        kind: K8sNoHostPath
      validation:
        openAPIV3Schema:
          properties:
            message:
              type: string
              default: "HostPath volumes are not allowed"
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snoHostPath
        violation[{"msg": msg}] {
            volume := input.review.object.spec.volumes[_]
            volume.hostPath
            msg := sprintf("HostPath volume %v is not allowed", [volume.name])
        }
