apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
