apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-root-user
  namespace: audit-zone
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1000
