apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    resources:
      - group: ""
        resources: ["pods"]
    namespaces: ["audit-zone"]
  
  - level: RequestResponse
    resources:
      - group: ""
        resources: ["pods"]
    namespaces: ["audit-zone"]
    verbs: ["create", "update"]
  
  - level: Request
    resources:
      - group: "constraints.gatekeeper.sh"
        resources: ["*"]
  
  - level: RequestResponse
    omitStages:
      - "RequestReceived"
    resources:
      - group: ""
        resources: ["events"]
